"""
Optimization Intelligence Service (Phases D1 + D2)

Phase D1: Deterministic semantic outcome classification for prompt optimization results.
Phase D2: Deterministic optimization value / efficiency classification.

Both phases are pure, model-agnostic, and operate without LLM calls.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Any, Dict, Optional

from app.services.strategy_router import EnhancementStrategy


class OptimizationOutcome(str, Enum):
    """
    Semantic outcome categories for prompt transformations.
    Inherits from str for JSON serialization and backwards compatibility.
    """
    ALREADY_EFFICIENT = "ALREADY_EFFICIENT"
    COMPRESSED = "COMPRESSED"
    USEFUL_EXPANSION = "USEFUL_EXPANSION"
    WORDING_REFINEMENT = "WORDING_REFINEMENT"
    UNNECESSARY_EXPANSION_PREVENTED = "UNNECESSARY_EXPANSION_PREVENTED"
    PRESERVED_AMBIGUOUS = "PRESERVED_AMBIGUOUS"


def classify_optimization_outcome(
    *,
    decision: str,
    original_tokens: int,
    enhanced_tokens: int,
    strategy: Optional[Any] = None,
    gate_result: Optional[Dict[str, Any]] = None,
    candidate_tokens: Optional[int] = None,
    mode: Optional[str] = None,
) -> OptimizationOutcome:
    """
    Deterministically classify the optimization outcome of an enhancement run.

    Classification rules:
    1. PRESERVED_AMBIGUOUS:
       - OptimizationGate bypassed an ambiguous / vague prompt.
    2. ALREADY_EFFICIENT:
       - Gate bypassed the prompt because it was already direct / structured / efficient, OR
       - StrategyRouter bypassed enhancement with NO_CHANGE, OR
       - Enhancement completed with unchanged text without model modification.
    3. COMPRESSED:
       - Candidate rewrite was accepted (decision == 'enhanced') AND final tokens < original tokens.
    4. WORDING_REFINEMENT:
       - Candidate rewrite was accepted (decision == 'enhanced') AND strategy == REFINE.
    5. USEFUL_EXPANSION:
       - Candidate rewrite was accepted (decision == 'enhanced') AND
         enhanced_tokens > original_tokens AND strategy in {STRUCTURE, CREATIVE_EXPAND} (or creative mode).
    6. UNNECESSARY_EXPANSION_PREVENTED:
       - Candidate rewrite was generated by model but rejected/reverted (decision == 'reverted').
    """
    # 1. Gate bypass checks
    if gate_result is not None:
        if gate_result.get("is_ambiguous"):
            return OptimizationOutcome.PRESERVED_AMBIGUOUS
        if not gate_result.get("should_optimize"):
            return OptimizationOutcome.ALREADY_EFFICIENT

    # 2. Reverted / Rejected candidate
    if decision == "reverted":
        return OptimizationOutcome.UNNECESSARY_EXPANSION_PREVENTED

    # 3. Unchanged bypass
    if decision == "unchanged":
        is_no_change_strategy = (
            strategy == EnhancementStrategy.NO_CHANGE
            or (isinstance(strategy, str) and strategy.lower() == "no_change")
        )
        if is_no_change_strategy:
            return OptimizationOutcome.ALREADY_EFFICIENT
        return OptimizationOutcome.ALREADY_EFFICIENT

    # 4. Error state fallback
    if decision == "error":
        return OptimizationOutcome.ALREADY_EFFICIENT

    # 5. Accepted enhancement (decision == "enhanced")
    if decision == "enhanced":
        # Check compression first
        if enhanced_tokens < original_tokens:
            return OptimizationOutcome.COMPRESSED

        is_refine_strategy = (
            strategy == EnhancementStrategy.REFINE
            or (isinstance(strategy, str) and strategy.lower() == "refine")
        )
        if is_refine_strategy:
            return OptimizationOutcome.WORDING_REFINEMENT

        # Expansion under STRUCTURE or CREATIVE_EXPAND or mode == 'creative'
        if enhanced_tokens > original_tokens:
            return OptimizationOutcome.USEFUL_EXPANSION

        # enhanced_tokens == original_tokens (streamlined / equivalent tokens)
        if is_refine_strategy:
            return OptimizationOutcome.WORDING_REFINEMENT
        return OptimizationOutcome.ALREADY_EFFICIENT

    return OptimizationOutcome.ALREADY_EFFICIENT


# =========================================================================
# Phase D2 — Optimization Decision Intelligence
# =========================================================================


class OptimizationValue(str, Enum):
    """
    Optimization value classification for accepted transformations.

    Orthogonal to OptimizationOutcome (D1) — grades the token-efficiency
    of the transformation, not what kind of transformation it was.
    """
    HIGH_VALUE_COMPRESSION = "HIGH_VALUE_COMPRESSION"
    MODERATE_COMPRESSION = "MODERATE_COMPRESSION"
    LOW_VALUE_COMPRESSION = "LOW_VALUE_COMPRESSION"
    JUSTIFIED_EXPANSION = "JUSTIFIED_EXPANSION"
    LOW_VALUE_EXPANSION = "LOW_VALUE_EXPANSION"
    WORDING_REFINEMENT = "WORDING_REFINEMENT"
    NO_OPTIMIZATION_NEEDED = "NO_OPTIMIZATION_NEEDED"


@dataclass(frozen=True)
class OptimizationValueResult:
    """Immutable D2 classification result."""
    value: OptimizationValue
    efficiency_score: float
    compression_ratio: Optional[float]
    expansion_ratio: Optional[float]
    token_delta: int
    token_delta_percent: float


def _is_structural_strategy(strategy: Optional[Any]) -> bool:
    """Return True for strategies that intentionally restructure/expand."""
    if strategy is None:
        return False
    if isinstance(strategy, EnhancementStrategy):
        return strategy in (
            EnhancementStrategy.STRUCTURE,
            EnhancementStrategy.CREATIVE_EXPAND,
        )
    if isinstance(strategy, str):
        return strategy.lower() in ("structure", "creative_expand")
    return False


def classify_optimization_value(
    *,
    outcome: OptimizationOutcome,
    original_tokens: int,
    enhanced_tokens: int,
    strategy: Optional[Any] = None,
    mode: Optional[str] = None,
    decision: str,
    structural_improvement: bool = False,
) -> OptimizationValueResult:
    """
    Phase D2: Classify the optimization value of an accepted transformation.

    Runs after D1 (classify_optimization_outcome).
    Deterministic. No LLM calls. No network calls.

    Args:
        outcome: D1's OptimizationOutcome classification.
        original_tokens: Token count of the original prompt.
        enhanced_tokens: Token count of the final accepted prompt.
        strategy: The EnhancementStrategy that was used.
        mode: The enhancement mode (concise, detailed, code, creative).
        decision: Phase C's decision (enhanced, reverted, unchanged, error).
        structural_improvement: Whether Phase C detected structural improvement
            in the accepted rewrite. Defaults to False for non-enhanced decisions.

    Returns:
        OptimizationValueResult with categorical label and numeric score.
    """
    # ── Shared computations ───────────────────────────────────────
    token_delta = enhanced_tokens - original_tokens
    safe_original = max(original_tokens, 1)
    token_delta_percent = round((token_delta / safe_original) * 100, 1)

    def _no_opt() -> OptimizationValueResult:
        return OptimizationValueResult(
            value=OptimizationValue.NO_OPTIMIZATION_NEEDED,
            efficiency_score=0.0,
            compression_ratio=None,
            expansion_ratio=None,
            token_delta=0,
            token_delta_percent=0.0,
        )

    # ── 1. Non-accepted transformations ───────────────────────────
    if decision in ("unchanged", "reverted", "error"):
        return _no_opt()

    # ── 2. D1 bypass states ───────────────────────────────────────
    if outcome in (
        OptimizationOutcome.ALREADY_EFFICIENT,
        OptimizationOutcome.PRESERVED_AMBIGUOUS,
        OptimizationOutcome.UNNECESSARY_EXPANSION_PREVENTED,
    ):
        return _no_opt()

    # ── 3. Compression (enhanced_tokens < original_tokens) ────────
    if token_delta < 0:
        compression_ratio = abs(token_delta) / safe_original
        abs_delta = abs(token_delta)

        if compression_ratio >= 0.20 and abs_delta >= 3:
            score = min(1.0, 0.7 + compression_ratio * 0.6)
            label = OptimizationValue.HIGH_VALUE_COMPRESSION
        elif compression_ratio >= 0.05 and abs_delta >= 3:
            score = 0.3 + compression_ratio * 2.0
            label = OptimizationValue.MODERATE_COMPRESSION
        else:
            score = max(0.05, compression_ratio)
            label = OptimizationValue.LOW_VALUE_COMPRESSION

        return OptimizationValueResult(
            value=label,
            efficiency_score=round(score, 2),
            compression_ratio=round(compression_ratio, 4),
            expansion_ratio=None,
            token_delta=token_delta,
            token_delta_percent=token_delta_percent,
        )

    # ── 4. REFINE wording refinement ──────────────────────────────
    if outcome == OptimizationOutcome.WORDING_REFINEMENT:
        if token_delta == 0:
            score = 0.50
        elif token_delta <= 4:
            score = 0.45
        else:
            # 5–8 tokens (Phase C caps REFINE at 8)
            score = 0.35

        return OptimizationValueResult(
            value=OptimizationValue.WORDING_REFINEMENT,
            efficiency_score=score,
            compression_ratio=None,
            expansion_ratio=(
                round(token_delta / safe_original, 4)
                if token_delta > 0
                else None
            ),
            token_delta=token_delta,
            token_delta_percent=token_delta_percent,
        )

    # ── 5. Expansion (enhanced_tokens > original_tokens) ──────────
    if token_delta > 0:
        expansion_ratio = token_delta / safe_original
        is_structural = _is_structural_strategy(strategy) or (
            strategy is None and mode in ("detailed", "code")
        )
        is_creative = mode == "creative"

        if is_structural or is_creative:
            if structural_improvement or is_creative:
                if expansion_ratio <= 1.0:
                    score = max(0.4, 0.8 - expansion_ratio * 0.4)
                else:
                    score = 0.35
                label = OptimizationValue.JUSTIFIED_EXPANSION
            else:
                score = 0.15 if expansion_ratio <= 0.10 else 0.10
                label = OptimizationValue.LOW_VALUE_EXPANSION
        else:
            # Non-structural, non-creative expansion that was accepted
            score = 0.10
            label = OptimizationValue.LOW_VALUE_EXPANSION

        return OptimizationValueResult(
            value=label,
            efficiency_score=round(score, 2),
            compression_ratio=None,
            expansion_ratio=round(expansion_ratio, 4),
            token_delta=token_delta,
            token_delta_percent=token_delta_percent,
        )

    # ── 6. Zero delta, non-REFINE ─────────────────────────────────
    return _no_opt()
